### ISSUE TITLE
timestamp returned format

### ISSUE THREAD

**Issue by jreynoso666** [marijnh/Postmodern#97] opened 2016-11-01 15:45 UTC
I have updated my quicklisp then I have a little problem
with "postmodern" , when I got the "last_update" row from my table I had a
universal time (number)  before the update I had a string with the date,
the row type is "timestamp with time zone".

**Comment by marijnh** [comment] 2016-11-01 15:48
So can you adjust your code to use the integer value instead?

**Comment by slyrus** [comment] 2016-11-01 15:56
@jreynoso666 Are you using simple-date? parsing time strings isn't much fun and simple-date handles the conversion from the integer value. check the simple-date-tests file for examples.

**Comment by jreynoso666** [comment] 2016-11-01 15:57
Thanks, I am going to check the examples.

**Comment by marijnh** [comment] 2016-11-01 15:59
@slyrus How is your decoding expressing the timezone, since CL universal-time values don't encode one?

**Comment by slyrus** [comment] 2016-11-01 16:17
I don't. timestamps with or without timezone are expressed as universal times. This time stuff makes my brain hurt.

**Comment by marijnh** [comment] 2016-11-01 16:20
> This time stuff makes my brain hurt.

If that's so, then I'm not really happy about the fact that you touched this part of the system. Would it make sense to delete the handler for "timestamp with time zone" values? Since if you're losing data, that's not much of a decoder.

**Comment by slyrus** [comment] 2016-11-01 17:18
I'd argue that we're not really losing data. The binary protocol only sends an 8-byte value for the timestamp (which is what's stored in the DB). What the postgres text protocol does is to adjust the time returned by the query to the timezone specified (usually the default for the session).

The binary handling of timestamp and timestamp with time zone types predates my involvement, but by changes did make row types containing timestamp and timestamptz now return binary -- I'm not sure if that's what @jreynoso666 is doing above or not. The other changes that could be affecting things is the changes to the readtable. But again, the handling of the timestamp and timestamptz -- and the corresponding encoding to simple-date types predates any of my changes.

But whether it's my code or not, I'm happy to help make the code "do the right thing" -- the problem is that's it's not exactly obvious what the right thing is.

**Comment by slyrus** [comment] 2016-11-01 17:20
While we're at it, an all text sql-readtable (an empty hashtable, I think) would probably be a useful thing to provide.

**Comment by marijnh** [comment] 2016-11-01 18:45
> The binary protocol only sends an 8-byte value for the timestamp (which is what's stored in the DB). What the postgres text protocol does is to adjust the time returned by the query to the timezone specified (usually the default for the session).

Oh, I see. I assumed the _value_ had a timezone associated with. In that case I guess you didn't really break anything _seriously_, your patches just changed the way in which this value was returned. Which I guess _is_ a breaking change, but a relatively benign one.

**Comment by slyrus** [comment] 2016-11-01 20:06
@jreynoso666 can you provide a sample of the results you're seeing from (the new version of) Postmodern?

@marijnh right, there are two possible things that could have changed the ways values were returned. 1) the timestamp (or timestamp with time zone) could have been in a row or ARRAY value, which used to return a text value of the timestamp (and the time zone if appropriate, adjusted by the libpq code for the sessions time zone) and would now return an integer version of the universal-time or, if the simple-date stuff is enabled, a simple-date::timestamp (corresponding to the universral time), or 2) reloading the new Postmodern in an existing image might have clobbered the sql-readtable such that he was getting an integer when he was expecting a simpl-date::timestamp. Trying to figure out which one was the issue here, but I'd argue things are 1) better now and 2) better tested now than they were before where row/arrays would give text and otherwise you'd get an integer or simple-date::timestamp depending on whether the simple date sql-readtable was in effect.

**Comment by jreynoso666** [comment] 2016-11-01 20:18
New version
((1684 3686496918) (1541 3684417022) (1675 3686322546) (1629 3685795354))

Old version
((1684 "2016-10-26 13:55:18.722037-05") (1541 "2016-10-02 12:10:22.448459-05")
 (1675 "2016-10-24 13:29:06.089188-05") (1629 "2016-10-18 11:02:34.642158-05"))

**Comment by slyrus** [comment] 2016-11-01 21:18
Ok, @jreynoso666  thanks! Is your query requesting either row or ARRAY types back from the database, e.g. select row(...) or select array_agg(...)?

**Comment by jreynoso666** [comment] 2016-11-01 22:11
(query (:select 'id_post_content 'last_update
		    :from 'posts_content
		    :where (:and
			    (:or (:= 'posts_content.access_type 1)
				 (:= 'posts_content.access_type 5))
			    (:is-null 'posts_content.album)
			    (:or
			     (:and
			      (:is-null 'start_publication)
			      (:is-null 'end_publication))
			     (:and
			      (:is-null 'start_publication)
			      (:>= 'end_publication (format-timestring nil (now))))
			     (:and
			      (:<= 'start_publication (format-timestring nil (now)))
			      (:is-null 'end_publication))
			     (:and
			      (:<= 'start_publication (format-timestring nil (now)))
			      (:>= 'end_publication (format-timestring nil (now))))))))

**Comment by slyrus** [comment] 2016-11-01 23:23
@marijnh Ok, I was wrong. I did introduce the change it turns out the sql-reader was there, but it wasn't being used until I added the clause in set-sql-datetime-readers turning it on. This produced the change that @jreynoso666 is now seeing.

I'm not a big fan of having timestamp return an int and timestamp with time zone return text, but we could make that the default, if you would like, returning the behavior back to how @jreynoso666 is expecting it.

**Comment by marijnh** [comment] 2016-11-02 08:52
Okay, that explains the change in behavior. Since in a way, the behavior got _more_ consistent (timestamps with and without zone are now treated the same) I think it makes sense to just commit to this behavior now, and ask people to update their code if they were relying on the old behavior.

**Comment by slyrus** [comment] 2016-11-02 16:32
@jreynoso666 one way to get the old behavior is to do:
```
(let ((*sql-readtable* (copy-sql-readtable)))
  (remhash 1184 *sql-readtable*)
  (with-test-connection
    (exec-query connection "select '2010-04-05 14:42:21.500'::timestamp with time zone"
                'list-row-reader)))
```

@marijnh should we offer an interface for removing sql readers (besides remhash ...) like making set-sql-reader accept nil for the function argument and removing the interpreter from hash table in that case?

**Comment by marijnh** [comment] 2016-11-02 16:54
Making `set-sql-reader` accept nil sounds okay.

**Comment by jreynoso666** [comment] 2016-11-04 16:11
Thanks, I have used the function and all works ok.

**Comment by slyrus** [comment] 2016-11-26 15:48
@jreynoso666 if all is working for you, will you close this issue? thanks!

**Closed** 2016-11-28 15:47 UTC
