### ISSUE TITLE
Azure Database for PostgreSQL server impossible to use because of gateway issue

### ISSUE THREAD

**Issue by sirherrbatka** [marijnh/Postmodern#282] opened 2021-08-02 18:54 UTC
Hello, 

Azure Database for PostgreSQL server uses the connection to a gateway which then redirects to the destination server based on the username. This results in fake usernames like user@host.azure.com (@host.azure.com part seems to be somehow stripped by the azure gateway and is not part of the actual username in the postgres). In cl-postgres this leads to "Invalid connection parameters specified. Check connection parameters, and try again." error signaled from the cl-postgres:authenticate function. This made me puzzled and I was unable to pinpoint core reason in a more precise manner. However I observed that omitting @hostname part of the username produces expected "invalid username format" error from but replacing the real @hostname part of the user with something bogus (like for instance user@trying.to.debug.the.problem) still produces "Invalid connection parameters specified. Check connection parameters, and try again." message. I have no idea what can produce such behavior.

**Comment by sabracrolleton** [comment] 2021-08-02 20:57
So what do your connection specs look like? Something like this?

```
(defparameter *connect-spec* '("my_database_name" "my_user_name" "my_user_password" "51.4.144.100" 5432))

(defmacro connect-now (&body body)
  `(let ((connection (apply 'open-database *connect-spec*)))
     (unwind-protect (progn ,@body)
       (close-database connection))))

(connect-now
 (exec-query connection "select 1"))
```

**Comment by sabracrolleton** [comment] 2021-08-02 21:28
The error message "Invalid connection parameters specified. Check connection parameters, and try again." is actually coming from the Postgresql database, not from cl-postgres. That implies to me that azure is not stripping out the @host.azure.com portion of the username. Just an fyi, I am unlikely to get to this for two to three weeks.

**Comment by sirherrbatka** [comment] 2021-08-03 07:19
I was using postmodern:connect. However, I just attempted to use open-database directly and it produces the same error.

Wounldn't lack of username stripping produce some login error instead?

**Comment by sirherrbatka** [comment] 2021-08-03 08:04
Oh, and most importantly, I was passing my_user_name@myhostname as the user.

**Comment by sabracrolleton** [comment] 2021-08-03 11:30
Postmodern does not have that error message, Postgresql does, so error mesage is coming from Postgresql. That does not mean that the issue does not originate in Postmodern. I have an idea what is going on, but it is just an idea at this point. 

What happens if you enclose the user in double quotes? In other words instead of 
`"my_user_name@myhostname"`
try
`"/"my_user_name@myhostname/""`

**Comment by sabracrolleton** [comment] 2021-08-03 12:07
That error message means that Postgresql received what it thought was an sql identifier which contained illegal characters. Postgresql should have been getting something that it identified as a string. Just as a test on a local network server (I still have to create an Azure account to debug your issue), I created a username at the psql (not Postmodern) command line:
`CREATE USER "davide@host.azure.com" WITH PASSWORD 'testpassword'; `
then switched to Postmodern at a CL REPL and successfully connected:
```
(with-connection '("test" "davide@host.azure.com" "testpassword" "192.168.5.202" :port 5434) 
  (list-tables))
```
So something seems to be going on between Postmodern and Azure creating the situation described at the top of this comment.

**Comment by sabracrolleton** [comment] 2021-08-03 14:55
I have replicated the symptoms. The cause is not immediately obvious, but you are right that it breaks in cl-postgres' authenticate function.

**Comment by sirherrbatka** [comment] 2021-08-03 14:59
Yeah, and I have no clue what is wrong either. Anyway, I expected this azure gateway to be transparent, but it is apparently not. Azure also offers "flexible PG server" which doesn't include @hostname bit and those work just fine.

**Comment by sabracrolleton** [comment] 2021-08-03 15:59
It is unfortunate that the connection parameters error does not provide any detail on the parameters received, for security reasons. It does make debugging harder. 

Looking at the server logs on Azure does not show any unsuccessful connections. I do not see any Azure settings to allow logging unsuccessful connections. 

Thank you for letting me know that "flexible PG server" works.

**Comment by sirherrbatka** [comment] 2021-08-03 16:38
I also failed to find such option in the azure configuration panel. I think that it simply does not exists, unfortunately. 

I know that it is possible to disable SSL for the Postgres, which should allow to sniff communication of CL-Postgres and compare it with some other database client (dbeaver application for instance). Maybe this would help to determine what is actually happening? 

Otherwise, I am afraid that I am at loss here.

**Comment by sabracrolleton** [comment] 2021-08-03 19:14
I think I tracked it down. Can you do me a favor? Try your connection, but add in an application-name parameter. In other words, something like:
```
(with-connection '("test" "yourname@yourdatabasename" "whatever_password_you_have"
                             "the_azure_database_host_name_combination" :application-name "misc-postmodern-tests") 
  (list-tables))
```
If you have a slash "/" in your password, it looks like it needs to be doubled at the moment -> "//" and a single quote in your password is likely to cause problems at the moment as well.

If this works, then we just need a default application name.

**Comment by sabracrolleton** [comment] 2021-08-04 19:34
Success. Fix committed today.

Quick summary. The problem is not originally where we thought it was (not the @whatever). Postgresql accepts an application name parameter in the connection parameters. This helps DBAs track bad behavior. Postmodern by default passes an empty string for that parameter. Azure's single instance gateway apparently does not know what to do with the empty string and passes on something that Postgresql thinks is an invalid connection parameter. Solution - always pass something in that application name parameter, so Postmodern will now do that by default. 

The test suite was run with no errors calling a Postgresql database running on an Azure server instance 8,000 km away from the location of the server running the Postmodern code. Yes, the speed of light did make the test responses painfully slow compared to what I am used to.

**Closed by sabracrolleton** 2021-08-04 19:34 UTC

**Comment by sirherrbatka** [comment] 2021-08-05 06:36
Huh, this is pretty interesting!
