### ISSUE TITLE
in cl-postgres.asd delete symbol :sbcl in line 21 if you want compile with sbcl

### ISSUE THREAD

**Issue by jh-midi** [marijnh/Postmodern#306] opened 2022-09-12 07:40 UTC
>sbcl don't use "usocket" then delete it at first place

 (defsystem "cl-postgres"
  :description "Low-level client library for PostgreSQL"
  :author "Marijn Haverbeke <marijnh@gmail.com>"
  :maintainer "Sabra Crolleton <sabra.crolleton@gmail.com>"
  :license "zlib"
  :version "1.33.4"
  :depends-on ("md5" "split-sequence" "ironclad" "cl-base64" "uax-15"
                 (:feature (:or ~~**:sbcl**~~ :allegro :ccl :clisp :genera
                                :armedbear :cmucl :lispworks)
                               "usocket")
                     (:feature :sbcl (:require :sb-bsd-sockets)))

**Comment by sabracrolleton** [comment] 2022-09-12 18:00
Are you saying it does not compile for you?

**Comment by jh-midi** [comment] 2022-09-12 19:28
it compile well if I remove :sbl from the line 21.
In the readme you can read : "The library depends on usocket (except on SBCL and ACL, where the built-in socket library is used" 

I am on sbcl 2.2.8

**Comment by jh-midi** [comment] 2022-09-13 18:02
here the result without removing :sbcl in line 21.

![postmodernSBCL](https://user-images.githubusercontent.com/86923160/189976341-797ba050-692d-42e9-93b6-7d034c32a278.PNG)

**Comment by sabracrolleton** [comment] 2022-09-13 23:20
Interesting. Are you running on Windows? This looks like https://bugs.launchpad.net/sbcl/+bug/1983355. A comment on that bug report claims that it is a usocket problem. I've commented on usocket at https://github.com/usocket/usocket/issues/86. 

I am not seeing this on a linux box or a mac (I do not happen to have a windows box handy at the moment), but if your fix works to solve the issue on windows, we can make that change and I can see what needs to be done for any issues that might cause for BSD types.

**Comment by jh-midi** [comment] 2022-09-14 08:16
> with sb-bsd-sockets  99%  of postmodern/tests pass on windows 10 
> I run postgres under msys and postgres user don't exist and it  is ok
> look at result below.


  Running test FAIL-INCLUDE-EXECUTE-FILE .
WARNING:
   PostgreSQL warning: la table « company_employees » n'existe pas, poursuite du traitement
 Did 1349 checks.
    Pass: 1342 (99%)
    Skip: 0 ( 0%)
    Fail: 7 ( 0%)

 Failure Details:
 --------------------------------
 DEFAULT-PRIVILEGES-2 in POSTMODERN-ROLES []: 
      Unexpected Error: #<CL-POSTGRES-ERROR::UNRECOGNIZED-CONFIGURATION-PARAMETER {1004A24963}>
Database error 42704: le rôle « postgres » n'existe pas
QUERY: reassign owned by a to postgres.
 --------------------------------
 --------------------------------
 DEFAULT-PRIVILEGES-1 in POSTMODERN-ROLES []: 
      Unexpected Error: #<CL-POSTGRES-ERROR::UNRECOGNIZED-CONFIGURATION-PARAMETER {1004A188E3}>
Database error 42704: le rôle « postgres » n'existe pas
QUERY: reassign owned by a to postgres.
 --------------------------------
 --------------------------------
 CREATE-DB-ROLE-0-1 in POSTMODERN-ROLES []: 
      Unexpected Error: #<CL-POSTGRES-ERROR:SYSTEM-ERROR {1004A04D13}>
Database error 58P01: n'a pas pu ouvrir le fichier de contrôle d'extension « E:/msys64/mingw64/share/postgresql/extension/pg_stat_statements.control » : No such file or directory
QUERY: CREATE EXTENSION IF NOT EXISTS pg_stat_statements;.
 --------------------------------
 --------------------------------
 BINARY-PREPARE-3-DROP-NO-TABLE-POOLED in POSTMODERN-BINARY-PREPARE []: 
      Unexpected Error: #<TYPE-ERROR expected-type: NUMBER datum: NIL>
The value
  NIL
is not of type
  NUMBER.
 --------------------------------
 --------------------------------
 BINARY-PREPARE-3-DROP-NO-TABLE in POSTMODERN-BINARY-PREPARE []: 
      Unexpected Error: #<TYPE-ERROR expected-type: NUMBER datum: NIL>
The value
  NIL
is not of type
  NUMBER.
 --------------------------------
 --------------------------------
 PREPARE-3-DROP-NO-TABLE-POOLED in POSTMODERN-PREPARE []: 
      Unexpected Error: #<TYPE-ERROR expected-type: NUMBER datum: NIL>
The value
  NIL
is not of type
  NUMBER.
 --------------------------------
 --------------------------------
 PREPARE-3-DROP-NO-TABLE in POSTMODERN-PREPARE []: 
      Unexpected Error: #<TYPE-ERROR expected-type: NUMBER datum: NIL>
The value
  NIL
is not of type
  NUMBER.
 --------------------------------

**Comment by binghe** [comment] 2022-09-14 08:31
Hi, new release (0.8.5) of usocket has just been made [1, 2], hopefully Quicklisp will incorporate it in a month. I've checked loading USOCKET on SBCL 2.2.8 (Windows), and everything seems fine.

[1] https://github.com/usocket/usocket/releases/tag/v0.8.5
[2] https://usocket.common-lisp.dev/releases/usocket-0.8.5.tar.gz

**Comment by jh-midi** [comment] 2022-09-14 09:09
Hi, it is a good usocket new, thank you !

**Comment by jh-midi** [comment] 2022-09-14 09:57
I tested the new version of usocket (8.5)and everything works fine with sbcl, with the same test results (99%)
And now we can use drakma and others ...

**Comment by sabracrolleton** [comment] 2022-09-14 13:20
Hi jh-midi,
Thank you for the error messages on the tests. I have found and fixed the first three, the last four are a bit more of a puzzle. 

If I could ask a favor, does the test prepare-3-drop-no-table immediately error or do any of the subtests pass?

Sabra

**Comment by jh-midi** [comment] 2022-09-14 14:32
> here running logs from postgres
[postgres_trace.log](https://github.com/marijnh/Postmodern/files/9567239/postgres_trace.log)
> and here the slime buffer
[test-run.txt](https://github.com/marijnh/Postmodern/files/9567244/test-run.txt)

**Comment by sabracrolleton** [comment] 2022-09-14 17:07
Thank you.

**Comment by sabracrolleton** [comment] 2022-09-15 19:13
Have made the change to :sbcl with respect to usocket, so closing this issue. Still tracking down the cause of the (drop-prepared-statement "all") failure on sbcl on windows.

**Closed by sabracrolleton** 2022-09-15 19:13 UTC
