### ISSUE TITLE
(:drop-table ...) is expanded incorrectly

### ISSUE THREAD

**Issue by tshatrov** [marijnh/Postmodern#239] opened 2020-06-29 12:02 UTC
```
(sql (:drop-table :if-exists table)))
```
expands to `"DROP TABLE IF EXISTS table"` since at least version 1.30. Previously it expanded to

```
(S-SQL::STRCAT (LIST "DROP TABLE IF EXISTS " (S-SQL:SQL-ESCAPE TABLE)))
```

This broke my code where `tables` is a list of tables (https://github.com/tshatrov/ichiran/issues/8).

```
(loop for table in (reverse tables)
        do (query (:drop-table :if-exists table)))
```

**Comment by phoe** [comment] 2020-06-29 12:08
Can reproduce. It seems that one cannot use variables in `pomo:sql` macro arguments anymore.

```lisp
POMO> (sql (:drop-table :if-exists table))
"DROP TABLE IF EXISTS table"

POMO> (s-sql::sql-expand '(:drop-table :if-exists table))
("DROP " "TABLE" " " "IF EXISTS " "table")
```

**Comment by tshatrov** [comment] 2020-06-29 12:10
Specifically the commit c6ead59313a506cddd8c3926e4936e0a9855eb69 is responsible for this new behavior.

**Comment by phoe** [comment] 2020-06-29 12:13
This looks like missing unit tests - `(sql (:drop-table :if-exists table))`, __without the quote on the symbol__, does not seem to occur anywhere in the unit tests added by that commit.

**Comment by sabracrolleton** [comment] 2020-06-29 13:15
Can you use the postmodern function (drop-table xyz :if-exists t :cascade t) while I look at this? At least that would allow you to use a list of variables.

**Comment by tshatrov** [comment] 2020-06-29 18:45
I'll use drop-table, but it seems to have become an exported symbol only very recently so I'll have to use import-from for compatibility.

**Comment by sabracrolleton** [comment] 2020-06-30 00:15
Does this work for you>
```

(defmacro def-drop-op (op-name word)
  `(def-sql-op ,op-name (&rest args)
     (let* ((concurrently (if (eq (car args) :concurrently)
                              (pop args)
                              nil))
            (if-exists (if (eq (car args) :if-exists)
                           (pop args)
                           nil))
            (name (pop args))
            (cascade (if (or (eq (car args) :cascade)
                             (eq (cadr args) :cascade))
                         t
                         nil)))
       `("DROP " ,,word " "
                 ,@(when concurrently '("CONCURRENTLY "))
                 ,@(when if-exists '("IF EXISTS "))
                 ,@(if (and (consp name) (eq :if-exists (car name)))
                       `("IF EXISTS " ,(car (sql-expand (cadr name))))
                     (cond ((stringp name)
                            (list name))
                           ((and (symbolp name)
                                (not (or (keywordp name) (eq name t)
                                         (eq name nil))))
                            (list `(to-sql-name ,name)))
                           (t (sql-expand name))))
                 ,@(when cascade '(" CASCADE"))))))
```

New test 
```
(test drop-table-variations
  (let ((table-var1 "table1")
        (table-var2 'table1))
    (is (equal (sql (:drop-table :if-exists table-var1 :cascade))
               "DROP TABLE IF EXISTS table1 CASCADE"))
    (is (equal (sql (:drop-table :if-exists "table1" :cascade))
               "DROP TABLE IF EXISTS table1 CASCADE"))
    (is (equal (sql (:drop-table :if-exists 'table1 :cascade))
               "DROP TABLE IF EXISTS table1 CASCADE"))
    (is (equal (sql (:drop-table :if-exists table-var2 :cascade))
               "DROP TABLE IF EXISTS table1 CASCADE"))
    (is (equal (sql (:drop-table :if-exists table-var1))
               "DROP TABLE IF EXISTS table1"))
    (is (equal (sql (:drop-table :if-exists "table1"))
               "DROP TABLE IF EXISTS table1"))
    (is (equal (sql (:drop-table :if-exists 'table1))
               "DROP TABLE IF EXISTS table1"))
    (is (equal (sql (:drop-table :if-exists table-var2))
               "DROP TABLE IF EXISTS table1"))
    (is (equal (sql (:drop-table table-var1 :cascade))
               "DROP TABLE table1 CASCADE"))
    (is (equal (sql (:drop-table "table1" :cascade))
               "DROP TABLE table1 CASCADE"))
    (is (equal (sql (:drop-table 'table1 :cascade))
               "DROP TABLE table1 CASCADE"))
    (is (equal (sql (:drop-table table-var2 :cascade))
               "DROP TABLE table1 CASCADE"))
    (is (equal (sql (:drop-table table-var1))
               "DROP TABLE table1"))
    (is (equal (sql (:drop-table "table1"))
               "DROP TABLE table1"))
    (is (equal (sql (:drop-table 'table1))
               "DROP TABLE table1"))
    (is (equal (sql (:drop-table table-var2))
               "DROP TABLE table1"))))
```

**Comment by sabracrolleton** [comment] 2020-06-30 01:15
Slightly more thorough version for your testing.
```

(defmacro def-drop-op (op-name word)
  `(def-sql-op ,op-name (&rest args)
     (let* ((concurrently (if (eq (car args) :concurrently)
                              (pop args)
                              nil))
            (if-exists (if (eq (car args) :if-exists)
                           (pop args)
                           nil))
            (name (pop args))
            (cascade (if (or (eq (car args) :cascade)
                             (eq (cadr args) :cascade))
                         t
                         nil)))
       `("DROP " ,,word " "
                 ,@(when concurrently '("CONCURRENTLY "))
                 ,@(when if-exists '("IF EXISTS "))
                 ,@(if (and (consp name) (eq :if-exists (car name)))
                       `("IF EXISTS " ,(car (cond ((stringp (cadr name))
                            (list (cadr name)))
                           ((and (symbolp (cadr name))
                                (not (or (keywordp (cadr name)) (eq (cadr name) t)
                                         (eq (cadr name) nil))))
                            (list `(to-sql-name ,(cadr name))))
                           (t (sql-expand (cadr name))))))
                     (cond ((stringp name)
                            (list (to-sql-name name)))
                           ((and (symbolp name)
                                (not (or (keywordp name) (eq name t)
                                         (eq name nil))))
                            (list `(to-sql-name ,name)))
                           (t (sql-expand name))))
                 ,@(when cascade '(" CASCADE"))))))
```

New test
```
(test drop-table-variations
  (let ((table-var1 "table1")
        (table-var2 'table1)
        (table-var3 "table-1"))
    (is (equal (sql (:drop-table :if-exists table-var1 :cascade))
               "DROP TABLE IF EXISTS table1 CASCADE"))
    (is (equal (sql (:drop-table :if-exists "table1" :cascade))
               "DROP TABLE IF EXISTS table1 CASCADE"))
    (is (equal (sql (:drop-table :if-exists 'table1 :cascade))
               "DROP TABLE IF EXISTS table1 CASCADE"))
    (is (equal (sql (:drop-table :if-exists table-var2 :cascade))
               "DROP TABLE IF EXISTS table1 CASCADE"))
    (is (equal (sql (:drop-table :if-exists table-var1))
               "DROP TABLE IF EXISTS table1"))
    (is (equal (sql (:drop-table :if-exists "table1"))
               "DROP TABLE IF EXISTS table1"))
    (is (equal (sql (:drop-table :if-exists 'table1))
               "DROP TABLE IF EXISTS table1"))
    (is (equal (sql (:drop-table :if-exists table-var2))
               "DROP TABLE IF EXISTS table1"))
    (is (equal (sql (:drop-table table-var1 :cascade))
               "DROP TABLE table1 CASCADE"))
    (is (equal (sql (:drop-table "table1" :cascade))
               "DROP TABLE table1 CASCADE"))
    (is (equal (sql (:drop-table 'table1 :cascade))
               "DROP TABLE table1 CASCADE"))
    (is (equal (sql (:drop-table table-var2 :cascade))
               "DROP TABLE table1 CASCADE"))
    (is (equal (sql (:drop-table table-var1))
               "DROP TABLE table1"))
    (is (equal (sql (:drop-table "table1"))
               "DROP TABLE table1"))
    (is (equal (sql (:drop-table 'table1))
               "DROP TABLE table1"))
    (is (equal (sql (:drop-table table-var2))
               "DROP TABLE table1"))
    (is (equal (sql (:drop-table 'george))
             "DROP TABLE george"))
    (is (equal (sql (:drop-table 'george-and-john))
               "DROP TABLE george_and_john"))
    (is (equal (sql (:drop-table :if-exists 'george))
               "DROP TABLE IF EXISTS george"))
    (is (equal (sql (:drop-table :if-exists 'george :cascade))
               "DROP TABLE IF EXISTS george CASCADE"))
    (is (equal (sql (:drop-table  (:if-exists 'george) :cascade))
               "DROP TABLE IF EXISTS george CASCADE"))
    (is (equal (sql (:drop-table "george"))
               "DROP TABLE george"))
    (is (equal (sql (:drop-table table-var3))
               "DROP TABLE table_1"))
    (is (equal (sql (:drop-table "george-and-john"))
               "DROP TABLE george_and_john"))
    (is (equal (sql (:drop-table :if-exists "george"))
               "DROP TABLE IF EXISTS george"))
    (is (equal (sql (:drop-table :if-exists "george" :cascade))
               "DROP TABLE IF EXISTS george CASCADE"))
    (is (equal (sql (:drop-table  (:if-exists "george") :cascade))
               "DROP TABLE IF EXISTS george CASCADE"))
    (is (equal (sql (:drop-table  (:if-exists table-var1) :cascade))
               "DROP TABLE IF EXISTS table1 CASCADE"))
    (is (equal (sql (:drop-table  (:if-exists table-var2) :cascade))
               "DROP TABLE IF EXISTS table1 CASCADE"))
    (is (equal (sql (:drop-table  (:if-exists "table-1") :cascade))
               "DROP TABLE IF EXISTS table_1 CASCADE"))))
```

**Comment by sabracrolleton** [comment] 2020-07-05 11:14
Fixed in this mornings commit

**Closed by sabracrolleton** 2020-07-05 11:14 UTC
