### ISSUE TITLE
:drop-table requires table name to be quoted, inconsistent with other operations

### ISSUE THREAD

**Issue by notmgsk** [marijnh/Postmodern#167] opened 2018-09-26 19:07 UTC
Some operations do not require names to be quoted. For example in `(query (:create-table testtbl ...))` the table name "testtbl" does not need to be quoted (in the lispy sense). However, the same name *does* need quoting in `(query (:drop-table 'testtbl))`. I cannot say whether this is intentional or a bug, but if it is intentional then I think it is inconsistent and perhaps confusing.

**Comment by sabracrolleton** [comment] 2018-09-27 04:27
Agreed we have some inconsistencies in this area. and the issue has existed for years (at least back to 2012). Text strings work consistently. Thus:

    (query (:create-table "testtbl" ...))
    (query (:drop-table "testtbl"))

Create-table works with an unquoted name (which prevents using variables)

    (query (:create-table testtbl ...))

but does not work with quoted names (in the lispy sense). That seems inconsistent with most of the rest of s-sql which likes quoted names.

    (query (:create-table 'testtbl1...))

Drop-table is the opposite. It works with the table name quoted (in the lispy sense)

    (query (:drop-table 'testtbl1))

but does not work with an unquoted name. This behavior allows testtbl1 to be a variable, which does work.)

    (query (:drop-table testtbl1))

So, given the long standing nature, how much breakage would solving the inconsistency create, which way should the inconsistency be solved (if at all) or should it just be hammered hard in documentation that everyone should just use strings?

Open for comments and suggestions from everyone.

**Comment by notmgsk** [comment] 2018-09-27 09:58
It's my first experience with Postmodern, so I can't offer any suggestions/concerns from experience, but taking the names-as-strings approach will alleviate my issue.

Clearly noting in the documentation that strings work best would of course be a start (not sure if that's already done) but perhaps maybe there could be a style warning raised if a name is not a string but is a symbol (lispy quoted or not).

**Comment by notmgsk** [comment] 2018-09-27 16:19
@sabracrolleton Trying to use strings for names but I'm running into an error.

```
(postmodern:query (:create-table "test-tbl" ((id :type int4 :primary-key t))))

(postmodern:query (:drop-table "test-tbl"))
```
gives the error
```
Database error 42601: syntax error at or near "E'test-tbl'"
QUERY: DROP TABLE E'test-tbl
```

**Comment by sabracrolleton** [comment] 2018-09-30 02:32
Forgot that postgresql does not accept escaped strings in drop table. Ok. Revisions in process to allow create-table to use quoted table names, which will make it consistent with what you expect. Thank you for bringing the issue up.  Obviously need to do the same thing will all the drop and create variations, so needs a lot of testing.

**Comment by sabracrolleton** [comment] 2018-10-07 17:51
Just committed. All the data definition s-sql query functions should now take quoted names.  Thank you for the push.

**Comment by abishek** [comment] 2020-01-21 03:35
I still have this problem. If I use a quoted string, create-table fails. But if I use unquoted strings, drop-table fails.

**Comment by sabracrolleton** [comment] 2020-01-21 14:38
Ok. Reopened issue.

**Comment by sabracrolleton** [comment] 2020-01-22 01:00
Just to be clear, are you using the s-sql variation (query (:drop-table xyz) or the utility function (drop-table xyz)?

On a clean system here creating tables, I am not reproducing the :create-table behavior:
```
(with-connection `("table_test", "sabrac", "some-password-string", "localhost" :port 5433)
        (query (:create-table 'table1 ((id :type int))))
        (query (:create-table "table2" ((id :type int))))
        (query (:create-table table3 ((id :type int))))
        (list-tables))
(:TABLE1 :TABLE2 :TABLE3)
```
Agree there is a problem with (query (:drop-table "xyz), however I had no issues with the (query (:create-table xzy)) regardless of single quote, quoted string or unquoted label.

Can you show the code you are using on the create-table problem?

**Comment by abishek** [comment] 2020-01-22 01:57
My code looks like this:

```
(defparameter *table-name* "article")

(defun get-connection ()
  (postmodern:connect-toplevel "my_db" "db_user" "db_pass" "localhost))

(defun setup-tables()
   (progn
        (get-connection)
        (drop-table)
        (create-table)
        (postmodern:disconnect-toplevel)))

(defun drop-table()
     (postmodern:query (:drop-table :if-exists *table-name*)))

(defun create-table ()
     (postmodern:query (:create-table *table-name*
                                                               ((id :type serial :primary-key t)
                                                                (content :type (varchar 300))))))

(setup-tables)
```

I am tried changing *table-name* to 'article. If I have "article", create works, but drop fails. But setting it to 'article caused my create to fail. Let me try that again and post the exact error message. Based on your example, that should work and I should be able to proceed with that.

Also, I am a little new to common lisp and maybe am doing something funny with my code. So please do let me know if the above usage is plain incorrect or sub-optimal. Thanks!

**Comment by abishek** [comment] 2020-01-22 02:15
Actually, I see the problem in my code. I don't know how I got the create function to work earlier (i have been randomly changing the code). Maybe let me first fix the code and get back when create works. Sorry!

**Comment by abishek** [comment] 2020-01-22 02:25
I found this sql-compile from your document at https://sites.google.com/site/sabraonthehill/postmodern-examples/postmodern-intro-to-s-sql

Based on this, I am able to get my code to work with *table-name* set to 'article. 

Sorry for wasting your time on this. I'll be more watchful going forward.
Thanks!

**Comment by sabracrolleton** [comment] 2020-01-23 01:18
Actually you did not waste my time because you did find an issue with drop table if the table-name is a quoted string.  So thank you.

**Comment by sabracrolleton** [comment] 2020-01-24 00:22
You can now use a string as a table name in the s-sql :drop-xyz sql-ops. I would still recommend using a quoted symbol table name however.

**Closed by sabracrolleton** 2020-01-24 00:22 UTC

**Comment by tshatrov** [comment] 2020-06-29 12:06
Possibly related to #239
